#!/usr/bin/env bash

# Do not source bashrc with set -e, as it may contain commands that fail, which would cause the pre-commit hook to fail unexpectedly.

if [ -f "$HOME/.bashrc" ]; then
  source "$HOME/.bashrc"
fi

# Safety on
set -e


# Skip if PRE_COMMIT_OVERRIDE is set
if [ "$PRE_COMMIT_OVERRIDE" = "1" ]; then
  echo '[pre-commit] Skipped (PRE_COMMIT_OVERRIDE=1)'
  exit 0
fi

# Install dependencies if needed
echo '[pre-commit] Installing dependencies...'
uv sync

echo '[pre-commit] Running pre-commit checks...'
uv run pytest

printf '\n[pre-commit] All checks passed!\n'
